// ptcg-play/src/app/shared/twinleaf-play-button/twinleaf-play-button.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';

@Component({
  selector: 'twinleaf-play-button',
  templateUrl: './twinleaf-play-button.component.html',
  styleUrls: ['./twinleaf-play-button.component.scss']
})
export class TwinleafPlayButtonComponent implements OnInit, OnDestroy {
  @Input() text: string = 'FIND MATCH';
  @Input() inQueue: boolean = false;
  @Input() loading: boolean = false;
  @Input() disabled: boolean = false;
  @Input() onCooldown: boolean = false;
  @Input() cooldownSeconds: number = 0;
  @Input() connectionError: boolean = false;
  @Input() width: string = '240px';
  @Input() height: string = '60px';
  @Input() fontSize: string = '14px';

  @Output() clicked = new EventEmitter<void>();

  ngOnInit(): void {
    // Component initialization
  }

  ngOnDestroy(): void {
    // Cleanup if needed
  }

  onClick(): void {
    if (!this.disabled && !this.loading && !this.connectionError) {
      this.clicked.emit();
    }
  }

  get buttonText(): string {
    if (this.inQueue) {
      return 'LEAVE QUEUE';
    }
    if (this.onCooldown) {
      return `COOLDOWN (${this.cooldownSeconds})`;
    }
    return this.text;
  }

  get buttonClasses(): string {
    const classes = ['play-button'];
    if (this.inQueue) {
      classes.push('in-queue');
    }
    if (this.connectionError) {
      classes.push('error');
    }
    return classes.join(' ');
  }

  get isDisabled(): boolean {
    return this.disabled || this.loading || this.connectionError || this.onCooldown;
  }
}

<button [class]="buttonClasses" [disabled]="isDisabled" (click)="onClick()" [style.width]="width"
  [style.height]="height" [style.font-size]="fontSize">

  <mat-spinner *ngIf="loading" diameter="20" style="display: inline-block; margin-right: 8px;">
  </mat-spinner>

  {{ buttonText }}
</button>

// ptcg-play-react/src/components/twinleaf/TwinleafPlayButton.tsx
import type { CSSProperties } from 'react';
import { cn } from '../../utils/cn';
import { TwinleafSpinner } from './TwinleafSpinner';
import styles from './TwinleafPlayButton.module.css';

export type TwinleafPlayButtonProps = {
  text?: string;
  inQueue?: boolean;
  loading?: boolean;
  disabled?: boolean;
  onCooldown?: boolean;
  cooldownSeconds?: number;
  connectionError?: boolean;
  width?: string;
  height?: string;
  fontSize?: string;
  className?: string;
  onClick?: () => void;
};

export function TwinleafPlayButton({
  text = 'FIND MATCH',
  inQueue = false,
  loading = false,
  disabled = false,
  onCooldown = false,
  cooldownSeconds = 0,
  connectionError = false,
  width = '240px',
  height = '60px',
  fontSize = '14px',
  className,
  onClick,
}: TwinleafPlayButtonProps) {
  const isDisabled = disabled || loading || connectionError || onCooldown;

  let buttonText = text;
  if (inQueue) {
    buttonText = 'LEAVE QUEUE';
  } else if (onCooldown) {
    buttonText = `COOLDOWN (${cooldownSeconds})`;
  }

  const style: CSSProperties = { width, height, fontSize };

  return (
    <button
      type="button"
      className={cn(
        styles.button,
        inQueue && styles.inQueue,
        connectionError && styles.error,
        className,
      )}
      style={style}
      disabled={isDisabled}
      onClick={() => {
        if (!isDisabled) {
          onClick?.();
        }
      }}
    >
      {loading ? <TwinleafSpinner size={20} /> : null}
      {buttonText}
    </button>
  );
}
