// ptcg-play/src/app/shared/cards/card-info-list-popup/card-info-list-popup.component.ts
import { Component, Inject } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog';
import { Card, CardList, SuperType } from 'ptcg-server';
import { CardInfoPaneOptions, CardInfoPaneAction } from '../card-info-pane/card-info-pane.component';
import { CardInfoPopupData, CardInfoPopupComponent } from '../card-info-popup/card-info-popup.component';


@Component({
  selector: 'ptcg-card-info-list-popup',
  templateUrl: './card-info-list-popup.component.html',
  styleUrls: ['./card-info-list-popup.component.scss']
})
export class CardInfoListPopupComponent {

  public card: Card;
  public cardList: CardList;
  public facedown: boolean;
  public allowReveal: boolean;
  public options: CardInfoPaneOptions;
  public sortDiscards: boolean = false;
  private originalDiscard: Card[] = [];

  constructor(
    private dialog: MatDialog,
    private dialogRef: MatDialogRef<CardInfoListPopupComponent>,
    @Inject(MAT_DIALOG_DATA) data: CardInfoPopupData,
  ) {
    this.card = data.card;
    this.cardList = data.cardList;
    this.allowReveal = data.allowReveal;
    this.facedown = data.facedown;
    this.options = data.options;
    this.originalDiscard = this.cardList.cards.slice(); // Clone discard pile
  }

  public async showCardInfo(card: Card): Promise<void> {
    this.card = card;

    const data: CardInfoPopupData = {
      card,
      facedown: this.facedown,
      options: this.options
    };

    const dialog = this.dialog.open(CardInfoPopupComponent, {
      maxWidth: '100%',
      width: '650px',
      data
    });

    const action = await dialog.afterClosed().toPromise();
    if (action) {
      this.close(action);
    }
  }

  public close(result?: CardInfoPaneAction) {
    this.dialogRef.close(result);
  }

  private getSortedCards(): Card[] {
    return this.cardList.cards.slice().sort((a, b) => {
      const typeOrder = (card: Card): number => {
        if (card.superType === SuperType.POKEMON) return 0;
        if (card.superType === SuperType.TRAINER) return 1;
        return 2;
      };

      const aType = typeOrder(a);
      const bType = typeOrder(b);
      if (aType !== bType) return aType - bType;
      if (a.set !== b.set) return a.set.localeCompare(b.set);
      return (parseInt(a.setNumber || '0', 10) - parseInt(b.setNumber || '0', 10));
    });
  }

  public onSortDiscardsChange(): void {
    if (this.sortDiscards) {
      const sorted = this.getSortedCards();
      this.cardList.cards = sorted;
    } else {
      this.cardList.cards = this.originalDiscard.slice(); // Restore discard order
    }
  }
}

<h2 mat-dialog-title translate>
  <!-- CARDS_LIST_OF_CARDS -->
</h2>

<mat-dialog-content>
  <div style="margin-bottom: 10px;">
    <label>
      <input type="checkbox" [(ngModel)]="sortDiscards" (change)="onSortDiscardsChange()" />
      Sort Discard
    </label>
  </div>

  <ptcg-card-list-pane [selected]="card" [cardList]="cardList" [facedown]="facedown" (cardClick)="showCardInfo($event)">
  </ptcg-card-list-pane>
</mat-dialog-content>

<mat-dialog-actions>
  <section class="ptcg-card-info-reveal-cards" *ngIf="allowReveal">
    <mat-checkbox color="primary" name="reveal-card" [checked]="!facedown" (change)="facedown = !facedown">
      {{ 'CARDS_REVEAL_CARDS' | translate }}
    </mat-checkbox>
  </section>
  <span class="ptcg-u-spacer"></span>
  <button mat-raised-button (click)="close()">
    {{ 'BUTTON_CLOSE' | translate }}
  </button>
</mat-dialog-actions>

// ptcg-play-react/src/card-info/CardInfoListPopup.tsx
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { Card, CardList } from 'ptcg-server';
import { SuperType as SuperTypeEnum } from 'ptcg-server';
import { CardFace } from '../components/cards/CardFace';
import type { CardInfoPaneOptions, CardInfoTableAction } from './CardInfoPane';
import { CardInfoPopup } from './CardInfoPopup';
import styles from './CardInfoListPopup.module.css';

export type CardInfoListPopupProps = {
  cardList: CardList;
  catalog: Card[];
  getScanUrl: (card: Card) => string;
  facedown?: boolean;
  allowReveal?: boolean;
  options?: CardInfoPaneOptions;
  isInGame?: boolean;
  onClose: () => void;
  onResolve?: (result: CardInfoTableAction & { cardList?: CardList }) => void;
};

function sortCardsLikeAngular(cards: Card[]): Card[] {
  return cards.slice().sort((a, b) => {
    const typeOrder = (c: Card): number => {
      if (c.superType === SuperTypeEnum.POKEMON) return 0;
      if (c.superType === SuperTypeEnum.TRAINER) return 1;
      return 2;
    };
    const aType = typeOrder(a);
    const bType = typeOrder(b);
    if (aType !== bType) return aType - bType;
    if (a.set !== b.set) return a.set.localeCompare(b.set);
    return (parseInt(a.setNumber || '0', 10) - parseInt(b.setNumber || '0', 10));
  });
}

export function CardInfoListPopup({
  cardList,
  catalog,
  getScanUrl,
  facedown = false,
  allowReveal = false,
  options,
  isInGame = true,
  onClose,
  onResolve,
}: CardInfoListPopupProps) {
  const { t } = useTranslation();
  const [sortDiscards, setSortDiscards] = useState(false);
  const [originalOrder] = useState(() => cardList.cards.slice());
  const [faceDownState, setFaceDownState] = useState(facedown);
  const [detailCard, setDetailCard] = useState<Card | null>(null);

  const displayCards = useMemo(
    () => (sortDiscards ? sortCardsLikeAngular(originalOrder) : originalOrder),
    [sortDiscards, originalOrder],
  );

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && !detailCard) onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose, detailCard]);

  return (
    <div
      className={styles.backdrop}
      role="presentation"
      onMouseDown={(e) => e.target === e.currentTarget && !detailCard && onClose()}
    >
      <div className={styles.panel} role="dialog" aria-modal="true">
        <h2 className={styles.title}>{t('CARDS_LIST_OF_CARDS', 'Cards')}</h2>
        <div className={styles.sortRow}>
          <label>
            <input
              type="checkbox"
              checked={sortDiscards}
              onChange={(e) => setSortDiscards(e.target.checked)}
            />{' '}
            Sort discard
          </label>
          {allowReveal ? (
            <label className={styles.reveal}>
              <input
                type="checkbox"
                checked={!faceDownState}
                onChange={() => setFaceDownState((v) => !v)}
              />{' '}
              {t('CARDS_REVEAL_CARDS')}
            </label>
          ) : null}
        </div>
        <div className={styles.grid}>
          {displayCards.map((c) => (
            <button
              key={`${c.fullName}-${c.id}`}
              type="button"
              className={styles.cardBtn}
              onClick={() => setDetailCard(c)}
            >
              <CardFace
                src={faceDownState ? '' : getScanUrl(c)}
                name={c.name}
                className={styles.cardThumb}
              />
            </button>
          ))}
        </div>
        <div className={styles.footer}>
          <button type="button" className={styles.closeBtn} onClick={onClose}>
            {t('BUTTON_CLOSE')}
          </button>
        </div>
      </div>

      {detailCard ? (
        <CardInfoPopup
          card={detailCard}
          cardList={cardList}
          facedown={faceDownState}
          catalog={catalog}
          getScanUrl={getScanUrl}
          onClose={() => setDetailCard(null)}
          isInGame={isInGame}
          options={options}
          onTableAction={
            onResolve
              ? (action) => {
                  onResolve({ ...action, cardList });
                  onClose();
                }
              : undefined
          }
        />
      ) : null}
    </div>
  );
}
