// ptcg-play-react/src/card-info/CardInfoPane.tsx
import { useCallback, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import type { Card, CardList, EnergyCard, PokemonCard, TrainerCard } from 'ptcg-server';
import { CardType, EnergyType, PowerType, SuperType, TrainerType } from 'ptcg-server';
import { CardSwapDialog } from './CardSwapDialog';
import { EnergyTypeIcon } from './EnergyTypeIcon';
import { isFavoriteCard, toggleFavoriteCard } from './favoriteCardsStorage';
import {
  getCardRuleText,
  getCardsWithSameName,
  getComputedHp,
  getCurrentHp,
  getDisplayAttacks,
  getDisplayPowers,
  getDisplayTagLabels,
  parseCardName,
  powerTypeLabel,
  stageLabel,
  transformEnergyText,
} from './cardInfoUtils';
import { HoverHighlight } from './HoverHighlight';
import { CardInfoImageColumn } from './CardInfoImageColumn';
import styles from './CardInfoPane.module.css';
import { TrainerTypeStrip } from './TrainerTypeStrip';

function IconHeart({ filled }: { filled: boolean }) {
  return filled ? (
    <svg width={20} height={20} viewBox="0 0 24 24" fill="currentColor" aria-hidden>
      <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z" />
    </svg>
  ) : (
    <svg width={20} height={20} viewBox="0 0 24 24" fill="currentColor" aria-hidden>
      <path d="M16.5 3c-1.74 0-3.41.81-4.5 2.09C10.91 3.81 9.24 3 7.5 3 4.42 3 2 5.42 2 8.5c0 3.78 3.4 6.86 8.55 11.54L12 21.35l1.45-1.32C18.6 15.36 22 12.28 22 8.5 22 5.42 19.58 3 16.5 3zm-4.4 15.55l-.1.1-.1-.1C7.14 18.24 4 15.39 4 8.5 4 6.5 5.5 5 7.5 5c1.54 0 3.04.99 3.57 2.36h1.87C13.46 5.99 14.96 5 16.5 5c2 0 3.5 1.5 3.5 3.5 0 6.89-3.14 9.74-7.9 13.05z" />
    </svg>
  );
}

export type CardInfoPaneOptions = {
  enableAttack?: boolean;
  enableTrainer?: boolean;
  enableRetreat?: boolean;
  enableAbility?: {
    useWhenInPlay?: boolean;
    useFromHand?: boolean;
    useFromDiscard?: boolean;
  };
};

/** Matches Angular `CardInfoPaneAction` (card is always the viewed card). */
export type CardInfoTableAction = {
  card: Card;
  attack?: string;
  ability?: string;
  trainer?: boolean;
  retreat?: boolean;
};

export type CardInfoPaneProps = {
  card: Card;
  /** In-play list (active/bench Pokémon) — used for HP bonus and damage like Angular `card-info-pane`. */
  cardList?: CardList;
  facedown: boolean;
  catalog: Card[];
  getScanUrl: (card: Card) => string;
  isInGame: boolean;
  options?: CardInfoPaneOptions;
  showTags?: boolean;
  cardTextKerning?: number;
  onCardSwap?: (event: { originalCard: Card; replacementCard: Card }) => void;
  /** In-game: ability / attack / retreat / trainer (stadium) selection for the 3D board. */
  onTableAction?: (action: CardInfoTableAction) => void;
  /** Parent (e.g. CardInfoPopup) renders {@link CardInfoImageColumn} beside this pane. */
  omitScanColumn?: boolean;
  swapOpen?: boolean;
  onSwapOpenChange?: (open: boolean) => void;
};

export function CardInfoPane({
  card,
  cardList,
  facedown,
  catalog,
  getScanUrl,
  isInGame,
  options = {},
  showTags = false,
  cardTextKerning = 0,
  onCardSwap,
  onTableAction,
  omitScanColumn = false,
  swapOpen: swapOpenProp,
  onSwapOpenChange,
}: CardInfoPaneProps) {
  const { t } = useTranslation();
  const [localSwapOpen, setLocalSwapOpen] = useState(false);
  const swapOpen = omitScanColumn ? (swapOpenProp ?? false) : localSwapOpen;
  const setSwapOpen = omitScanColumn
    ? (v: boolean) => onSwapOpenChange?.(v)
    : setLocalSwapOpen;
  const [, favBump] = useState(0);
  const bumpFavorite = useCallback(() => favBump((n) => n + 1), []);

  const alternatives = useMemo(() => getCardsWithSameName(catalog, card), [catalog, card]);

  function trainerSubtitle(trainerT: TrainerType): string {
    switch (trainerT) {
      case TrainerType.SUPPORTER:
        return t('CARDS_SUPPORTER');
      case TrainerType.STADIUM:
        return t('CARDS_STADIUM');
      case TrainerType.TOOL:
        return t('CARDS_POKEMON_TOOL');
      default:
        return t('CARDS_ITEM');
    }
  }

  const kerningStyle = { letterSpacing: `${cardTextKerning}px` } as const;

  const enabledAbilities = useMemo(() => {
    const m: Record<string, boolean> = {};
    const e = options.enableAbility;
    if (!e) return m;
    for (const power of getDisplayPowers(card)) {
      const ok =
        !!(e.useWhenInPlay && power.useWhenInPlay) ||
        !!(e.useFromDiscard && power.useFromDiscard) ||
        !!(e.useFromHand && power.useFromHand);
      if (ok) m[power.name] = true;
    }
    return m;
  }, [card, options.enableAbility]);

  const shouldEnableAttacks = !!options.enableAttack && getDisplayAttacks(card).length > 0;
  const shouldEnableRetreat = !!(card.superType === SuperType.POKEMON && options.enableRetreat);
  const enableTrainerPlay = !!options.enableTrainer;

  const parsed = parseCardName(card.name);
  const pokemon = card as PokemonCard;
  const trainer = card as TrainerCard;
  const energy = card as EnergyCard;

  const tagLabels = getDisplayTagLabels(card, showTags);

  const onSwapSelect = (replacement: Card) => {
    setSwapOpen(false);
    onCardSwap?.({ originalCard: card, replacementCard: replacement });
  };

  const favoriteToggle = (
    <button
      type="button"
      className={styles.favoriteButton}
      title={isFavoriteCard(card) ? t('FAVORITE_REMOVE') : t('FAVORITE_ADD')}
      onClick={() => {
        toggleFavoriteCard(card);
        bumpFavorite();
      }}
    >
      <IconHeart filled={isFavoriteCard(card)} />
    </button>
  );

  return (
    <div className={omitScanColumn ? styles.paneEmbed : styles.pane}>
      {!omitScanColumn ? (
        <CardInfoImageColumn
          card={card}
          catalog={catalog}
          facedown={facedown}
          getScanUrl={getScanUrl}
          isInGame={isInGame}
          onSwapClick={() => setSwapOpen(true)}
        />
      ) : null}

      {!facedown && card.superType === SuperType.POKEMON && (
        <div className={styles.textCol}>
          <div className={styles.title}>
            {parsed.prefix ? (
              <>
                <span className={styles.subtitleSetCode}>{parsed.prefix}</span>
                <span>{parsed.rest}</span>
              </>
            ) : (
              <span>{card.name}</span>
            )}
            <span className={styles.subtitleSetCode}>
              {card.set} {card.setNumber}
            </span>
            <div className={styles.spacer} />
            <div className={styles.subtitleHp}>
              <span className={styles.subtitleHpUnit}>{t('CARDS_HP')}</span>
              <span className={styles.subtitleHpValue}>
                {getCurrentHp(card, cardList) ?? '—'}/{getComputedHp(card, cardList) ?? '—'}
              </span>
            </div>
            <div className={styles.subtitleCardType}>
              <EnergyTypeIcon type={pokemon.cardType} style={{ transform: 'translateY(12px)' }} />
              {pokemon.additionalCardTypes?.map((t) => (
                <EnergyTypeIcon key={String(t)} type={t} style={{ transform: 'translateY(12px)' }} />
              ))}
            </div>
          </div>
          <div className={styles.subtitle}>
            <div className={styles.subtitleStage}>{stageLabel(pokemon)}</div>
            <div className={styles.spacer} />
            {tagLabels.length > 0 && (
              <>
                <div className={styles.subtitleTags}>
                  {tagLabels.map((tag) => (
                    <span key={tag} className={styles.tag}>
                      {tag}
                    </span>
                  ))}
                </div>
                <div className={styles.spacer} />
              </>
            )}
            {pokemon.evolvesFrom ? (
              <div className={styles.subtitleEvolvesFrom}>{t('CARDS_EVOLVES_FROM', { name: pokemon.evolvesFrom })}</div>
            ) : null}
            {pokemon.evolvesTo && pokemon.evolvesTo.length > 0 ? (
              <div className={styles.subtitleEvolvesTo}>Evolves into {pokemon.evolvesTo.join(', ')}</div>
            ) : null}
          </div>

          {getDisplayPowers(card).map((power) => (
            <HoverHighlight
              key={power.name}
              enabled={!!enabledAbilities[power.name]}
              onClick={
                onTableAction && enabledAbilities[power.name]
                  ? () => onTableAction({ card, ability: power.name })
                  : undefined
              }
            >
              <div className={styles.power}>
                <div className={styles.powerHeader}>
                  <div className={styles.powerType}>
                    {powerTypeLabel(power.powerType) ? (
                      <span className={power.powerType === PowerType.POKEBODY ? styles.pokeBody : styles.ability}>
                        {powerTypeLabel(power.powerType)}
                      </span>
                    ) : null}
                  </div>
                  <div className={styles.powerName}>{power.name}</div>
                </div>
                <div
                  className={styles.cardText}
                  style={kerningStyle}
                  dangerouslySetInnerHTML={{ __html: transformEnergyText(power.text ?? '') }}
                />
              </div>
            </HoverHighlight>
          ))}

          {getDisplayAttacks(card).map((attack) => (
            <HoverHighlight
              key={attack.name}
              enabled={shouldEnableAttacks}
              onClick={
                onTableAction && shouldEnableAttacks
                  ? () => onTableAction({ card, attack: attack.name })
                  : undefined
              }
            >
              <div className={styles.attack}>
                <div className={styles.attackHeader}>
                  <div className={styles.attackCost}>
                    {attack.cost.length === 0 ? (
                      <EnergyTypeIcon type={CardType.NONE} style={{ transform: 'translateY(3px)' }} />
                    ) : (
                      attack.cost.map((cost, i) => (
                        <EnergyTypeIcon
                          key={`${attack.name}-cost-${i}`}
                          type={cost}
                          style={{ transform: 'translateY(3px)' }}
                        />
                      ))
                    )}
                  </div>
                  <div className={styles.attackName}>{attack.name}</div>
                  <div className={styles.spacer} />
                  {attack.damage > 0 ? (
                    <div className={styles.attackDamage}>
                      {attack.damage}
                      {attack.damageCalculation ? ` ${attack.damageCalculation}` : ''}
                    </div>
                  ) : null}
                </div>
                <div
                  className={styles.cardText}
                  style={kerningStyle}
                  dangerouslySetInnerHTML={{ __html: transformEnergyText(attack.text ?? '') }}
                />
              </div>
            </HoverHighlight>
          ))}

          <div className={styles.stats}>
            <div className={styles.statsItem}>
              <div className={styles.statsItemHeader}>{t('CARDS_WEAKNESS')}</div>
              {(pokemon.weakness ?? []).map((w, i) => (
                <div key={i} className={styles.statsItemValue}>
                  <div className={styles.statsItemValueType}>
                    <EnergyTypeIcon type={w.type} style={{ transform: 'translateY(5px)' }} />
                  </div>
                  <div className={styles.statsItemValueModifier}>{w.value ? `+${w.value}` : 'x2'}</div>
                </div>
              ))}
            </div>
            <div className={styles.statsItem}>
              <div className={styles.statsItemHeader}>{t('CARDS_RESISTANCE')}</div>
              {(pokemon.resistance ?? []).map((r, i) => (
                <div key={i} className={styles.statsItemValue}>
                  <div className={styles.statsItemValueType}>
                    <EnergyTypeIcon type={r.type} style={{ transform: 'translateY(5px)' }} />
                  </div>
                  <div className={styles.statsItemValueModifier}>{r.value}</div>
                </div>
              ))}
            </div>
            <HoverHighlight
              enabled={shouldEnableRetreat}
              className={styles.statsHighlight}
              onClick={
                onTableAction && shouldEnableRetreat
                  ? () => onTableAction({ card, retreat: true })
                  : undefined
              }
            >
              <div className={styles.statsItem}>
                <div className={styles.statsItemHeader}>{t('CARDS_RETREAT_COST')}</div>
                <div className={styles.statsItemValue}>
                  <div className={styles.statsItemValueType}>
                    {(pokemon.retreat ?? []).map((cost, i) => (
                      <EnergyTypeIcon key={i} type={cost} style={{ transform: 'translateY(5px)' }} />
                    ))}
                  </div>
                </div>
              </div>
            </HoverHighlight>
          </div>

          {getCardRuleText(card) ? (
            <div className={styles.power}>
              <div className={styles.powerHeader}>
                <div className={styles.powerName}>{card.name}</div>
              </div>
              <div
                className={styles.cardText}
                style={kerningStyle}
                dangerouslySetInnerHTML={{ __html: transformEnergyText(getCardRuleText(card)) }}
              />
            </div>
          ) : null}
        </div>
      )}

      {!facedown && card.superType === SuperType.ENERGY && (
        <div className={styles.textCol}>
          <div className={styles.title}>
            <span>{card.name}</span>{' '}
            <span className={styles.subtitleSetCode}>
              {card.set} {card.setNumber}
            </span>
            {!isInGame ? favoriteToggle : null}
          </div>
          <div className={styles.subtitle}>
            <div className={styles.subtitleStage}>
              {energy.energyType === EnergyType.BASIC ? t('CARDS_BASIC_ENERGY') : t('CARDS_SPECIAL_ENERGY')}
            </div>
            <div className={styles.spacer} />
            <div className={styles.subtitleCardType}>
              <TrainerTypeStrip />
            </div>
          </div>
          {getCardRuleText(card) ? (
            <div className={styles.power}>
              <div className={styles.powerHeader}>
                <div className={styles.powerName}>{card.name}</div>
              </div>
              <div
                className={styles.cardText}
                style={kerningStyle}
                dangerouslySetInnerHTML={{ __html: transformEnergyText(getCardRuleText(card)) }}
              />
            </div>
          ) : null}
          {getDisplayPowers(card).map((power) => (
            <HoverHighlight
              key={power.name}
              enabled={!!enabledAbilities[power.name]}
              onClick={
                onTableAction && enabledAbilities[power.name]
                  ? () => onTableAction({ card, ability: power.name })
                  : undefined
              }
            >
              <div className={styles.power}>
                <div className={styles.powerHeader}>
                  <div className={styles.powerType}>
                    {powerTypeLabel(power.powerType) ? (
                      <span className={styles.ability}>{powerTypeLabel(power.powerType)}</span>
                    ) : null}
                  </div>
                  <div className={styles.powerName}>{power.name}</div>
                </div>
                <div
                  className={styles.cardText}
                  style={kerningStyle}
                  dangerouslySetInnerHTML={{ __html: transformEnergyText(power.text ?? '') }}
                />
              </div>
            </HoverHighlight>
          ))}
        </div>
      )}

      {!facedown && card.superType === SuperType.TRAINER && (
        <div className={styles.textCol}>
          <div className={styles.title}>
            <span>{card.name}</span>{' '}
            <span className={styles.subtitleSetCode}>
              {card.set} {card.setNumber}
            </span>
            {!isInGame ? favoriteToggle : null}
          </div>
          <div className={styles.subtitle}>
            <div className={styles.subtitleStage}>{trainerSubtitle(trainer.trainerType)}</div>
            <div className={styles.spacer} />
            <div className={styles.subtitleCardType}>
              <TrainerTypeStrip type={trainer.trainerType} />
            </div>
          </div>
          {getDisplayPowers(card).map((power) => (
            <HoverHighlight
              key={power.name}
              enabled={!!enabledAbilities[power.name]}
              onClick={
                onTableAction && enabledAbilities[power.name]
                  ? () => onTableAction({ card, ability: power.name })
                  : undefined
              }
            >
              <div className={styles.power}>
                <div className={styles.powerHeader}>
                  <div className={styles.powerType}>
                    {powerTypeLabel(power.powerType) ? (
                      <span className={styles.ability}>{powerTypeLabel(power.powerType)}</span>
                    ) : null}
                  </div>
                  <div className={styles.powerName}>{power.name}</div>
                </div>
                <div
                  className={styles.cardText}
                  style={kerningStyle}
                  dangerouslySetInnerHTML={{ __html: transformEnergyText(power.text ?? '') }}
                />
              </div>
            </HoverHighlight>
          ))}
          {getDisplayAttacks(card).map((attack) => (
            <HoverHighlight
              key={attack.name}
              enabled={shouldEnableAttacks}
              onClick={
                onTableAction && shouldEnableAttacks
                  ? () => onTableAction({ card, attack: attack.name })
                  : undefined
              }
            >
              <div className={styles.attack}>
                <div className={styles.attackHeader}>
                  <div className={styles.attackCost}>
                    {attack.cost.length === 0 ? <EnergyTypeIcon type={CardType.NONE} /> : null}
                    {attack.cost.map((cost, i) => (
                      <EnergyTypeIcon key={i} type={cost} />
                    ))}
                  </div>
                  <div className={styles.attackName}>{attack.name}</div>
                  <div className={styles.spacer} />
                  {attack.damage > 0 ? <div className={styles.attackDamage}>{attack.damage}</div> : null}
                </div>
                <div
                  className={styles.cardText}
                  style={kerningStyle}
                  dangerouslySetInnerHTML={{ __html: transformEnergyText(attack.text ?? '') }}
                />
              </div>
            </HoverHighlight>
          ))}
          <HoverHighlight
            enabled={enableTrainerPlay}
            onClick={
              onTableAction && enableTrainerPlay ? () => onTableAction({ card, trainer: true }) : undefined
            }
          >
            {getCardRuleText(card) ? (
              <div className={styles.power}>
                <div className={styles.powerHeader}>
                  <div className={styles.powerName}>{card.name}</div>
                </div>
                <div
                  className={styles.cardText}
                  style={kerningStyle}
                  dangerouslySetInnerHTML={{ __html: transformEnergyText(getCardRuleText(card)) }}
                />
              </div>
            ) : null}
          </HoverHighlight>
        </div>
      )}

      {!facedown && card.superType === SuperType.NONE && (
        <div className={styles.textCol}>
          <div className={styles.title}>{card.name}</div>
        </div>
      )}

      {facedown && (
        <div className={styles.textCol}>
          <div className={styles.title}>{t('CARDS_UNKNOWN')}</div>
          <div className={styles.power}>
            <div className={styles.cardText}>{t('CARDS_FACE_DOWN_HINT')}</div>
          </div>
        </div>
      )}

      <CardSwapDialog
        open={swapOpen}
        onClose={() => setSwapOpen(false)}
        currentCard={card}
        alternativeCards={alternatives}
        getScanUrl={getScanUrl}
        onSelect={onSwapSelect}
      />
    </div>
  );
}

// ptcg-play/src/app/shared/cards/card-info-pane/card-info-pane.component.ts
import { Component, OnChanges, Input, Output, EventEmitter } from '@angular/core';
import { Card, SuperType, Stage, PowerType, EnergyType, TrainerType, PokemonCard, TrainerCard } from 'ptcg-server';
import { MatDialog } from '@angular/material/dialog';

import { CardImagePopupComponent } from '../card-image-popup/card-image-popup.component';

export interface CardInfoPaneOptions {
  enableAbility?: {
    useWhenInPlay?: boolean;
    useFromHand?: boolean;
    useFromDiscard?: boolean;
  };
  enableAttack?: boolean;
  enableTrainer?: boolean;
}

export interface CardInfoPaneAction {
  card: Card;
  attack?: string;
  ability?: string;
  trainer?: boolean;
}

@Component({
  selector: 'ptcg-card-info-pane',
  templateUrl: './card-info-pane.component.html',
  styleUrls: ['./card-info-pane.component.scss']
})
export class CardInfoPaneComponent implements OnChanges {

  @Input() card: Card;
  @Input() facedown: boolean;
  @Input() options: CardInfoPaneOptions = {};
  @Output() action = new EventEmitter<any>();

  public enabledAbilities: {[name: string]: boolean} = {};
  public SuperType = SuperType;
  public Stage = Stage;
  public PowerType = PowerType;
  public EnergyType = EnergyType;
  public TrainerType = TrainerType;

  constructor(
    private dialog: MatDialog
  ) { }

  public clickAction(action: CardInfoPaneAction) {
    action.card = this.card;
    this.action.next(action);
  }

  public ngOnChanges() {
    // Build map of enabled powers
    if (this.options.enableAbility) {
      this.enabledAbilities = this.buildEnabledAbilities();
    }
  }

  private buildEnabledAbilities(): {[name: string]: boolean} {
    const enabledAbilities: {[name: string]: boolean} = {};
    if (this.card && this.card.superType === SuperType.POKEMON || this.card.superType === SuperType.TRAINER) {
      const pokemonCard = this.card as PokemonCard;
      pokemonCard.powers.forEach(power => {
        if ((this.options.enableAbility.useWhenInPlay && power.useWhenInPlay)
          || (this.options.enableAbility.useFromDiscard && power.useFromDiscard)
          || (this.options.enableAbility.useFromHand && power.useFromHand)) {
          enabledAbilities[power.name] = true;
          }
        });
        const trainerCard = this.card as TrainerCard;
        trainerCard.powers.forEach(power => {
          if ((this.options.enableAbility.useWhenInPlay && power.useWhenInPlay)
            || (this.options.enableAbility.useFromDiscard && power.useFromDiscard)
            || (this.options.enableAbility.useFromHand && power.useFromHand)) {
            enabledAbilities[power.name] = true;
          }
      });
    }
    return enabledAbilities;
  }

  public showCardImage(card: Card, facedown: boolean): Promise<void> {
    const dialog = this.dialog.open(CardImagePopupComponent, {
      maxWidth: '100%',
      data: { card, facedown }
    });

    return dialog.afterClosed().toPromise()
      .catch(() => false);
  }

}

<div class="ptcg-card-info-pane">
  <div class="ptcg-card-info-image">
    <ptcg-card [card]="card" [artworksContext]="cardList || null" [class.cardback]="facedown"
      (click)="showCardImage(card, facedown)"></ptcg-card>

    <!-- Swap Button - Only show when not in game and not facedown -->
    <div class="swap-button-container" *ngIf="!isInGame() && !facedown">
      <button mat-icon-button class="swap-button" (click)="openCardSwapDialog()"
        [disabled]="getCardsWithSameName().length === 0"
        [matTooltip]="getCardsWithSameName().length > 0 ? 'Swap with alternative printing' : 'No alternative printings available'">
        <mat-icon>swap_horiz</mat-icon>
      </button>
    </div>
  </div>

  <div class="ptcg-card-info-text" *ngIf="!facedown && card.superType === SuperType.POKEMON">
    <div class="title">
      <ng-container *ngIf="parseCardName(card.name).prefix; else normalName">
        <span class="card-name-prefix">{{parseCardName(card.name).prefix}}</span>
        <span>{{parseCardName(card.name).rest}}</span>
      </ng-container>
      <ng-template #normalName>
        <span>{{card.name}}</span>
      </ng-template>
      <span class="subtitle-set-code">{{card.set}} {{card.setNumber}}</span>
      <span class="regulation-mark" *ngIf="card.regulationMark && card.regulationMark != 'ENERGY'">{{card.regulationMark}}</span>
      <div class="ptcg-u-spacer"></div>
      <div class="subtitle-hp">
        <span class="subtitle-hp-unit" translate>CARDS_HP</span>
        <span class="subtitle-hp-value">{{getCurrentHp()}}/{{getComputedHp()}}</span>
      </div>
      <div class="subtitle-card-type">
        <ptcg-energy [type]="card.cardType" style="transform: translateY(12px);"></ptcg-energy>
        <ng-container *ngIf="card.additionalCardTypes">
          <ptcg-energy *ngFor="let type of card.additionalCardTypes" [type]="type"
            style="transform: translateY(12px);"></ptcg-energy>
        </ng-container>
      </div>
    </div>
    <div class="subtitle">
      <div class="subtitle-stage" [ngSwitch]="card.stage">
        <span *ngSwitchCase="Stage.BASIC" [ngSwitch]="card.tags.includes(CardTag.BABY)">
          <span *ngSwitchCase="true" translate>CARDS_BABY_POKEMON</span>
          <span *ngSwitchDefault translate>CARDS_BASIC</span>
        </span>
        <span *ngSwitchCase="Stage.RESTORED" translate>CARDS_RESTORED</span>
        <span *ngSwitchCase="Stage.STAGE_1" translate>CARDS_STAGE_1</span>
        <span *ngSwitchCase="Stage.STAGE_2" translate>CARDS_STAGE_2</span>
        <span *ngSwitchCase="Stage.MEGA" translate>CARDS_MEGA</span>
        <span *ngSwitchCase="Stage.BREAK" translate>CARDS_BREAK</span>
        <span *ngSwitchCase="Stage.LV_X" translate>CARDS_LV_X</span>
        <span *ngSwitchCase="Stage.VMAX" translate>CARDS_VMAX</span>
        <span *ngSwitchCase="Stage.VSTAR" translate>CARDS_VSTAR</span>
        <span *ngSwitchCase="Stage.VUNION" translate>CARDS_VUNION</span>
        <span *ngSwitchCase="Stage.LEGEND" translate>CARDS_LEGEND</span>
      </div>
      <div class="ptcg-u-spacer"></div>
      <div class="subtitle-tags" *ngIf="getDisplayTags().length > 0">
        <span class="tag" *ngFor="let tag of getDisplayTags()">{{ tag }}</span>
      </div>
      <div class="ptcg-u-spacer" *ngIf="getDisplayTags().length > 0"></div>
      <div class="subtitle-evolves-from" *ngIf="card.evolvesFrom">
        {{ 'CARDS_EVOLVES_FROM' | translate: { name: card.evolvesFrom } }}
      </div>
      <div class="subtitle-evolves-to" *ngIf="card.evolvesTo && card.evolvesTo.length > 0">
        Evolves into {{ card.evolvesTo.join(', ') }}
      </div>
    </div>

    <ptcg-hover-highlight *ngFor="let power of getDisplayPowers()"
      (click)="enabledAbilities[power.name] && clickAction({ability: power.name})"
      [enabled]="enabledAbilities[power.name]">
      <div class="power">
        <div class="power-header">
          <div class="power-type" *ngIf="power.powerType !== PowerType.TRAINER_ABILITY" [ngSwitch]="power.powerType">
            <div class="ability" *ngSwitchCase="PowerType.ABILITY" translate>CARDS_ABILITY</div>
            <div class="ability" *ngSwitchCase="PowerType.POKEPOWER" translate>CARDS_POKE_POWER</div>
            <div class="ability" *ngSwitchCase="PowerType.POKEMON_POWER" translate>CARDS_POKEMON_POWER</div>
            <div class="poke-body" *ngSwitchCase="PowerType.POKEBODY" translate>CARDS_POKE_BODY</div>
            <div class="ability" *ngSwitchCase="PowerType.ANCIENT_TRAIT" translate>CARDS_ANCIENT_TRAIT</div>
          </div>
          <div class="power-name">
            {{ power.name }}
          </div>
        </div>
        <div class="card-text" [innerHTML]="formatCardText(power.text)" [ngStyle]="getCardTextKerningStyle()">
        </div>
      </div>
    </ptcg-hover-highlight>

    <ptcg-hover-highlight *ngFor="let attack of getDisplayAttacks()"
      (click)="shouldEnableAttacks() && clickAction({attack: attack.name})" [enabled]="shouldEnableAttacks()">
      <div class="attack">
        <div class="attack-header">
          <div class="attack-cost">
            <ptcg-energy *ngIf="attack.cost.length === 0" style="transform: translateY(3px);"></ptcg-energy>
            <ptcg-energy *ngFor="let cost of attack.cost" [type]="cost"
              style="transform: translateY(3px);"></ptcg-energy>
          </div>
          <div class="attack-name">
            {{ attack.name }}
          </div>
          <div class="ptcg-u-spacer"></div>
          <div class="attack-damage" *ngIf="attack.damage > 0">
            {{ attack.damage }}{{attack.damageCalculation ? ' ' + attack.damageCalculation : ''}}
          </div>
        </div>
        <div class="card-text" [innerHTML]="formatCardText(attack.text)" [ngStyle]="getCardTextKerningStyle()">
        </div>
      </div>
    </ptcg-hover-highlight>

    <div class="power" *ngFor="let ruleBox of getDisplayRuleBoxes()">
      <div class="power-header">
        <div class="power-type" *ngIf="ruleBox.isRuleBox">
          <div class="ability">Rule Box</div>
        </div>
        <div class="power-name">
          {{ ruleBox.name }}
        </div>
      </div>
      <div class="card-text" [innerHTML]="formatCardText(ruleBox.text)" [ngStyle]="getCardTextKerningStyle()"></div>
    </div>

    <div class="stats">
      <div class="stats-item">
        <div class="stats-item-header" translate>CARDS_WEAKNESS</div>
        <div class="stats-item-value" *ngFor="let weakness of card.weakness">
          <div class="stats-item-value-type">
            <ptcg-energy [type]="weakness.type" style="transform: translateY(5px);"></ptcg-energy>
          </div>
          <div class="stats-item-value-modifier">
            {{ weakness.value ? '+' + weakness.value : 'x2' }}
          </div>
        </div>
      </div>

      <div class="stats-item">
        <div class="stats-item-header" translate>CARDS_RESISTANCE</div>
        <div class="stats-item-value" *ngFor="let resistance of card.resistance">
          <div class="stats-item-value-type">
            <ptcg-energy [type]="resistance.type" style="transform: translateY(5px);"></ptcg-energy>
          </div>
          <div class="stats-item-value-modifier">
            {{ resistance.value }}
          </div>
        </div>
      </div>

      <ptcg-hover-highlight (click)="shouldEnableRetreat() && clickAction({retreat: true})"
        [enabled]="shouldEnableRetreat()">
        <div class="stats-item">
          <div class="stats-item-header" translate>CARDS_RETREAT_COST</div>
          <div class="stats-item-value">
            <div class="stats-item-value-type">
              <ptcg-energy *ngFor="let cost of card.retreat" [type]="cost"
                style="transform: translateY(5px);"></ptcg-energy>
            </div>
          </div>
        </div>
      </ptcg-hover-highlight>
    </div>

    <!-- <div *ngIf="card.superType === SuperType.POKEMON">
      <span>Current HP: {{ getCurrentHp() }}/{{ getComputedHp() }}</span>
    </div> -->

    <div class="power" *ngIf="card.text">
      <div class="power-header">
        <div class="power-name" translate>
          {{ card.name }}
        </div>
      </div>
      <div class="card-text" [innerHTML]="formatCardText(card.text)" [ngStyle]="getCardTextKerningStyle()"></div>
    </div>

  </div>

  <div class="ptcg-card-info-text" *ngIf="!facedown && card.superType === SuperType.ENERGY">
    <div class="title">
      <span>{{card.name}}</span> <span class="subtitle-set-code">{{card.set}} {{card.setNumber}}</span>
      <span class="regulation-mark"
        *ngIf="card.regulationMark && card.regulationMark != 'ENERGY'">{{card.regulationMark}}</span>
      <button mat-icon-button class="favorite-button" *ngIf="!isInGame() && card.superType === SuperType.ENERGY"
        (click)="toggleFavorite()" [matTooltip]="isFavoriteCard() ? 'Remove from favorites' : 'Add to favorites'">
        <mat-icon>{{isFavoriteCard() ? 'favorite' : 'favorite_border'}}</mat-icon>
      </button>
    </div>
    <div class="subtitle">
      <div class="subtitle-stage" [ngSwitch]="card.energyType">
        <span *ngSwitchCase="EnergyType.BASIC" translate>CARDS_BASIC_ENERGY</span>
        <span *ngSwitchCase="EnergyType.SPECIAL" translate>CARDS_SPECIAL_ENERGY</span>
      </div>
      <div class="ptcg-u-spacer"></div>
      <div class="subtitle-tags" *ngIf="getDisplayTags().length > 0">
        <span class="tag" *ngFor="let tag of getDisplayTags()">{{ tag }}</span>
      </div>
      <div class="ptcg-u-spacer"></div>
      <div class="subtitle-card-type">
        <ptcg-trainer-type></ptcg-trainer-type>
      </div>
    </div>

    <div class="power" *ngIf="card.text">
      <div class="power-header">
        <div class="power-name" translate>
          {{ card.name }}
        </div>
      </div>
      <div class="card-text" [innerHTML]="formatCardText(card.text)" [ngStyle]="getCardTextKerningStyle()"></div>
    </div>

    <ptcg-hover-highlight *ngFor="let power of getDisplayPowers()"
      (click)="enabledAbilities[power.name] && clickAction({ability: power.name})"
      [enabled]="enabledAbilities[power.name]">
      <div class="power">
        <div class="power-header">
          <div class="power-type" *ngIf="power.powerType !== PowerType.ENERGY_ABILITY" [ngSwitch]="power.powerType">
            <div class="ability" *ngSwitchCase="PowerType.ABILITY" translate>CARDS_ABILITY</div>
          </div>
          <div class="power-name">
            {{ power.name }}
          </div>
        </div>
        <div class="card-text" [innerHTML]="formatCardText(power.text)" [ngStyle]="getCardTextKerningStyle()">
        </div>
      </div>
    </ptcg-hover-highlight>

    <div class="power" *ngFor="let ruleBox of getDisplayRuleBoxes()">
      <div class="power-header">
        <div class="power-type" *ngIf="ruleBox.isRuleBox">
          <div class="ability">Rule Box</div>
        </div>
        <div class="power-name">
          {{ ruleBox.name }}
        </div>
      </div>
      <div class="card-text" [innerHTML]="formatCardText(ruleBox.text)" [ngStyle]="getCardTextKerningStyle()"></div>
    </div>

  </div>

  <div class="ptcg-card-info-text" *ngIf="!facedown && card.superType === SuperType.TRAINER">
    <div class="title">
      <span>{{card.name}}</span> <span class="subtitle-set-code">{{card.set}} {{card.setNumber}}</span>
      <span class="regulation-mark"
        *ngIf="card.regulationMark && card.regulationMark != 'ENERGY'">{{card.regulationMark}}</span>
      <button mat-icon-button class="favorite-button" *ngIf="!isInGame() && card.superType === SuperType.TRAINER"
        (click)="toggleFavorite()" [matTooltip]="isFavoriteCard() ? 'Remove from favorites' : 'Add to favorites'">
        <mat-icon>{{isFavoriteCard() ? 'favorite' : 'favorite_border'}}</mat-icon>
      </button>
    </div>
    <div class="subtitle">
      <div class="subtitle-stage" [ngSwitch]="card.trainerType">
        <span *ngSwitchDefaultCase translate>CARDS_ITEM</span>
        <span *ngSwitchCase="TrainerType.ITEM" translate>CARDS_ITEM</span>
        <span *ngSwitchCase="TrainerType.SUPPORTER" translate>CARDS_SUPPORTER</span>
        <span *ngSwitchCase="TrainerType.STADIUM" translate>CARDS_STADIUM</span>
        <span *ngSwitchCase="TrainerType.TOOL" translate>CARDS_POKEMON_TOOL</span>
      </div>
      <div class="ptcg-u-spacer"></div>
      <div class="subtitle-tags" *ngIf="getDisplayTags().length > 0">
        <span class="tag" *ngFor="let tag of getDisplayTags()">{{ tag }}</span>
      </div>
      <div class="ptcg-u-spacer"></div>
      <div class="subtitle-card-type">
        <ptcg-trainer-type [type]="card.trainerType"></ptcg-trainer-type>
      </div>
    </div>

    <ptcg-hover-highlight (click)="options.enableTrainer && clickAction({trainer: true})" [enabled]="options.enableTrainer">
      <div class="power" *ngIf="card.text">
        <div class="power-header">
          <div class="power-name" translate>
            {{ card.name }}
          </div>
        </div>
        <div class="card-text" [innerHTML]="formatCardText(card.text)" [ngStyle]="getCardTextKerningStyle()"></div>
      </div>
    </ptcg-hover-highlight>

    <ptcg-hover-highlight *ngFor="let power of getDisplayPowers()"
      (click)="enabledAbilities[power.name] && clickAction({ability: power.name})"
      [enabled]="enabledAbilities[power.name]">
      <div class="power">
        <div class="power-header">
          <div class="power-type" *ngIf="power.powerType !== PowerType.TRAINER_ABILITY" [ngSwitch]="power.powerType">
            <div class="ability" *ngSwitchCase="PowerType.ABILITY" translate>CARDS_ABILITY</div>
          </div>
          <div class="power-name">
            {{ power.name }}
          </div>
        </div>
        <div class="card-text" [innerHTML]="formatCardText(power.text)" [ngStyle]="getCardTextKerningStyle()">
        </div>
      </div>
    </ptcg-hover-highlight>

    <ptcg-hover-highlight *ngFor="let attack of getDisplayAttacks()"
      (click)="shouldEnableAttacks() && clickAction({attack: attack.name})" [enabled]="shouldEnableAttacks()">
      <div class="attack">
        <div class="attack-header">
          <div class="attack-cost">
            <ptcg-energy *ngIf="attack.cost.length === 0"></ptcg-energy>
            <ptcg-energy *ngFor="let cost of attack.cost" [type]="cost"></ptcg-energy>
          </div>
          <div class="attack-name">
            {{ attack.name }}
          </div>
          <div class="ptcg-u-spacer"></div>
          <div class="attack-damage" *ngIf="attack.damage > 0">
            {{ attack.damage }}
          </div>
        </div>
        <div class="card-text" [innerHTML]="formatCardText(attack.text)" [ngStyle]="getCardTextKerningStyle()">
        </div>
      </div>
    </ptcg-hover-highlight>

    <div class="power" *ngFor="let ruleBox of getDisplayRuleBoxes()">
      <div class="power-header">
        <div class="power-type" *ngIf="ruleBox.isRuleBox">
          <div class="ability">Rule Box</div>
        </div>
        <div class="power-name">
          {{ ruleBox.name }}
        </div>
      </div>
      <div class="card-text" [innerHTML]="formatCardText(ruleBox.text)" [ngStyle]="getCardTextKerningStyle()"></div>
    </div>

  </div>

  <div class="ptcg-card-info-text" *ngIf="!facedown && card.superType === SuperType.NONE">
    <div class="title">
      {{card.name}}
    </div>
  </div>

  <div class="ptcg-card-info-text" *ngIf="facedown">
    <div class="title" translate>
      CARDS_UNKNOWN
    </div>
    <div class="power">
      <div class="card-text" translate>CARDS_FACE_DOWN_HINT</div>
    </div>
  </div>
</div>
